---
- hosts: "dev"
  become: true
  remote_user: ubuntu
  vars_files:
    - files/secrets/credentials.yml
  roles:
    - role: geerlingguy.docker
      docker_compose: true  # Active l'installation de Docker Compose
    - role: role-odoo
    - role: apache-static-site